#!/bin/sh

xsetroot -cursor_name left_ptr

echo "Xft.dpi: 192" | xrdb -merge -
xset r rate 190 75
xinput set-prop "ELAN0672:00 04F3:3187 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ELAN0672:00 04F3:3187 Touchpad" "libinput Accel Speed" 0.5
xinput set-prop "ELAN0672:00 04F3:3187 Touchpad" "libinput Natural Scrolling Enabled" 1

export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx

xhost +SI:localuser:$USER
export _JAVA_AWT_WM_NONREPARENTING=1

feh --bg-scale ~/Pictures/wallpapers/mountain_4k.jpg &
picom --backend glx --glx-no-stencil --vsync &
fcitx5 &
autorandr --change &

export SBCL_HOME="/usr/lib/sbcl"
exec stumpwm
