#!/bin/bash

while getopts "m:r:d:f:k:" opt; do
    case $opt in
        m)
            monitor="${OPTARG}"
            echo "Monitor: ${monitor}"
            ;;
        r)
            resolution="${OPTARG}"
            echo "Resolution: ${resolution}"
            ;;
        d)
            dpi="${OPTARG}"
            echo "DPI: ${dpi}"
            ;;
        f)
            font_size="${OPTARG}"
            echo "Font size: ${font_size}"
            ;;
        k)
            keyboard="${OPTARG}"
            echo "Keyboard: ${keyboard}"
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            exit 1            
            ;;
        :)
            echo "Option -$OPTARG requires an argument."
            exit 1
            ;;
    esac
done

if [[ -n "${monitor}" && -n "${resolution}" ]]; then
    xrandr --output ${monitor} --mode ${resolution} --primary
else
    echo "monitor or resolution is not given, skip xrandr setup"
fi

if [[ -n "${dpi}" ]]; then
    echo "Xft.dpi: $dpi" | xrdb -merge -
    kill -9 $(pgrep -a chrome | grep -v chrome-remote-desktop | awk '{print $1}') # cleanup chrome process with old dpi
else
    echo "dpi is not given, skip xrdb setup"
fi

if [[ -n "${font_size}" ]]; then
    emacsclient --eval "(internal-set-lisp-face-attribute 'default :font (font-spec :size $font_size :dpi $dpi) 0)"
else
    echo "font_size is not given, skip emacs font setup"
fi

if [[ -n "${keyboard}" ]]; then
    setxkbmap
    xmodmap .Xmodmap_${keyboard}
else
    echo "keyboard is not given, skip xmodmap setup"
fi
