#!/bin/sh

# Set keyboard repeat rate.
xset r rate 190 75

# Set default cursor.
xsetroot -cursor_name left_ptr

# specify input method
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx

# export GDK_SCALE=2
# export QT_SCALE_FACTOR=2
# export QT_AUTO_SCREEN_SCALE_FACTOR=0

# some useful trays and daemons
fcitx5 &
# blueman-tray &
# nm-applet &
# volumeicon &
# xfce4-power-manager &

# Disable access control for the current user.
xhost +SI:localuser:$USER

# Make Java applications aware this is a non-reparenting window manager.
export _JAVA_AWT_WM_NONREPARENTING=1

xrandr --newmode 3840x2160 60 3840 0 0 0 2160 0 0 0
xrandr --newmode 3840x2400 60 3840 0 0 0 2400 0 0 0
xrandr --addmode DUMMY0 3840x2160
xrandr --addmode DUMMY0 3840x2400

# launch emacs and enable exwm
# exec emacsclient -c
emacs --eval "(progn (exwm-wm-mode) (server-start))"
