(in-package :stumpwm)

(set-module-dir "~/.stumpwm.d/modules")

(load-module "battery-portable")
(load-module "command-history")
(load-module "globalwindows")
(load-module "net")
(load-module "notify")
(load-module "pamixer")
(load-module "screenshot")
(load-module "shell-command-history")
(load-module "swm-gaps")
(load-module "ttf-fonts")
(load-module "xft-fix")
