#!/usr/bin/bash

date
echo ""

args=""
serial=""
device_cnt=$(adb devices | head -n-1 | tail -n+2 | wc -l)

if [[ ! -z $1 ]]
then
	serial=$1
	args="-s $serial"
elif [[ $device_cnt = 1 ]]
then	
	serial=$(adb devices | head -n-1 | tail -n+2 | awk '{print $1}')
	args="-s $serial"
else
	echo "more than 1 devices and no serial number is give" &> 2
	exit 1
fi

adb $args reboot
adb $args wait-for-device
adb $args root

sleep 30

# zygote_pid=$(adb $args shell ps -A | grep zygote64 | awk '{print $2}')
# zygote_vm_area_cnt=$(adb $args shell cat /proc/${zygote_pid}/maps | wc -l)
# echo "zygote vm_area count: ${zygote_vm_area_cnt}"

echo "<<< after boot to home and idle 30s >>>"
parse_vmas $serial
echo ""
slabinfo parse $serial

echo -e "\n=======================================================================\n"

echo "<<< stop framework >>>"
adb $args shell stop
sleep 30
parse_vmas $serial
echo ""
slabinfo parse $serial
